#!/bin/bash

# Check if correct number of arguments is provided
if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <profile_name> <path_to_extensions_file>"
  exit 1
fi

# Assign arguments to variables
PROFILE_NAME="$1"
EXTENSIONS_FILE="$2"

# Check if the file exists
if [[ ! -f $EXTENSIONS_FILE ]]; then
  echo "File $EXTENSIONS_FILE does not exist. Please provide a valid file."
  exit 1
fi

# Loop through each line in the file and run the command
while IFS= read -r extension || [[ -n $extension ]]; do
  if [[ -n $extension ]]; then
    # echo "Installing extension: $extension using profile: $PROFILE_NAME"
    code --profile "$PROFILE_NAME" --install-extension "$extension"
  fi
done < "$EXTENSIONS_FILE"

# Generated by ChatGPT. What, do I look like a scripting wizard?
