matches:
  - trigger: ";d"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%y%m%d"
  - trigger: ";er"
    replace: "🔴"
  - trigger: ";ey"
    replace: "🟡"
  - trigger: ";eg"
    replace: "🟢"
  - trigger: ";ec"
    replace: "✅"
  - trigger: ";ex"
    replace: "❌"
  - trigger: ";ef"
    replace: "🔥"
  - trigger: ";es"
    replace: "⭐️"
